<?php

namespace HopitalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccueilRepository extends EntityRepository
{
}
