<?php

namespace HopitalBundle\Repository;

/**
 * BaseDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasedocRepository extends AbstractRepository
{
}