<?php
namespace HopitalBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRepository extends EntityRepository
{
}