<?php

namespace HopitalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentationRepository extends EntityRepository
{
}
