<?php

namespace HopitalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends AbstractRepository
{
}
