<?php

namespace HopitalBundle\Repository;

/**
 * GroupemessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupemessageRepository extends AbstractRepository
{
}
