<?php

namespace HopitalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasRepository extends AbstractRepository
{
}
