<?php
namespace HopitalBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * MedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalRepository extends AbstractRepository
{
}