<?php

namespace HopitalBundle\Repository;

/**
 * NoteserviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteserviceRepository extends AbstractRepository
{
}
