<?php

namespace HopitalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlansRepository extends EntityRepository
{
}
