communication_edit:
    path:     /{id}/edit
    defaults: { _controller: "HopitalBundle:Communication:edit" }
    methods:  [GET, POST]

communication_delete:
    path:     /{id}/delete
    defaults: { _controller: "HopitalBundle:Communication:delete" }
    methods:  DELETE



communication_articles_index:
    path:     /articles
    defaults: { _controller: "HopitalBundle:Articles:index" }
    methods:  GET

communication_articles_new:
    path:     /articles/new
    defaults: { _controller: "HopitalBundle:Articles:new" }
    methods:  [GET, POST]

communication_articles_edit:
    path:     /articles/{id}/edit
    defaults: { _controller: "HopitalBundle:Articles:edit" }
    methods:  [GET, POST]

communication_articles_delete:
    path:     /articles/{id}/delete
    defaults: { _controller: "HopitalBundle:Articles:delete" }
    methods:  DELETE



communication_lienssites_index:
    path:     /lienssites
    defaults: { _controller: "HopitalBundle:Lienssites:index" }
    methods:  GET

communication_lienssites_new:
    path:     /lienssites/new
    defaults: { _controller: "HopitalBundle:Lienssites:new" }
    methods:  [GET, POST]

communication_lienssites_edit:
    path:     /lienssites/{id}/edit
    defaults: { _controller: "HopitalBundle:Lienssites:edit" }
    methods:  [GET, POST]

communication_lienssites_delete:
    path:     /lienssites/{id}/delete
    defaults: { _controller: "HopitalBundle:Lienssites:delete" }
    methods:  DELETE



communication_lettreinfo_index:
    path:     /lettreinfo
    defaults: { _controller: "HopitalBundle:Lettreinfo:index" }
    methods:  GET

communication_lettreinfo_new:
    path:     /lettreinfo/new
    defaults: { _controller: "HopitalBundle:Lettreinfo:new" }
    methods:  [GET, POST]

communication_lettreinfo_edit:
    path:     /lettreinfo/{id}/edit
    defaults: { _controller: "HopitalBundle:Lettreinfo:edit" }
    methods:  [GET, POST]

communication_lettreinfo_delete:
    path:     /lettreinfo/{id}/delete
    defaults: { _controller: "HopitalBundle:Lettreinfo:delete" }
    methods:  DELETE




communication_direction_index:
    path:     /direction
    defaults: { _controller: "HopitalBundle:Direction:index" }
    methods:  GET

communication_direction_new:
    path:     /direction/new
    defaults: { _controller: "HopitalBundle:Direction:new" }
    methods:  [GET, POST]

communication_direction_edit:
    path:     /direction/{id}/edit
    defaults: { _controller: "HopitalBundle:Direction:edit" }
    methods:  [GET, POST]

communication_direction_delete:
    path:     /direction/{id}/delete
    defaults: { _controller: "HopitalBundle:Direction:delete" }
    methods:  DELETE






communication_ght_index:
    path:     /ght
    defaults: { _controller: "HopitalBundle:Ght:index" }
    methods:  GET

communication_ght_new:
    path:     /ght/new
    defaults: { _controller: "HopitalBundle:Ght:new" }
    methods:  [GET, POST]

communication_ght_edit:
    path:     /ght/{id}/edit
    defaults: { _controller: "HopitalBundle:Ght:edit" }
    methods:  [GET, POST]

communication_ght_delete:
    path:     /ght/{id}/delete
    defaults: { _controller: "HopitalBundle:Ght:delete" }
    methods:  DELETE
