demarches_certification_index:
    path:     /certification
    defaults: { _controller: "HopitalBundle:Certification:index" }
    methods:  GET

demarches_certification_new:
    path:     /certification/new
    defaults: { _controller: "HopitalBundle:Certification:new" }
    methods:  [GET, POST]

demarches_certification_edit:
    path:     /certification/{id}/edit
    defaults: { _controller: "HopitalBundle:Certification:edit" }
    methods:  [GET, POST]

demarches_certification_delete:
    path:     /certification/{id}/delete
    defaults: { _controller: "HopitalBundle:Certification:delete" }
    methods:  DELETE




demarches_epp_index:
    path:     /epp
    defaults: { _controller: "HopitalBundle:Epp:index" }
    methods:  GET

demarches_epp_index_show:
    path:     /{id}/epp_show
    defaults: { _controller: "HopitalBundle:Epp:index_show" }
    methods:  [GET, POST]

demarches_epp_index_admin:
    path:     /epp_admin
    defaults: { _controller: "HopitalBundle:Epp:index_admin" }
    methods:  GET

demarches_epprubrique_edit:
    path:     /epprubrique/{id}/edit
    defaults: { _controller: "HopitalBundle:Epp:editRubrique" }
    methods:  [GET, POST]

demarches_epprubrique_delete:
    path:     /epprubrique/{id}/delete
    defaults: { _controller: "HopitalBundle:Epp:deleteRubrique" }
    methods:  DELETE

demarches_epp_new:
    path:     /epp/new
    defaults: { _controller: "HopitalBundle:Epp:new" }
    methods:  [GET, POST]

demarches_epp_edit:
    path:     /epp/{id}/edit
    defaults: { _controller: "HopitalBundle:Epp:edit" }
    methods:  [GET, POST]

demarches_epp_delete:
    path:     epp/{id}/delete
    defaults: { _controller: "HopitalBundle:Epp:delete" }
    methods:  DELETE

demarches_epprubrique_new:
    path:     /epprubrique/new
    defaults: { _controller: "HopitalBundle:Epp:newRubrique" }
    methods:  [GET, POST]



demarches_paqss_index:
    path:     /paqss
    defaults: { _controller: "HopitalBundle:Paqss:index" }
    methods:  GET

demarches_paqss_index_admin:
    path:     /paqss_admin
    defaults: { _controller: "HopitalBundle:Paqss:index_admin" }
    methods:  GET

demarches_paqss_index_show:
    path:     /paqss/{id}/show
    defaults: { _controller: "HopitalBundle:Paqss:index_show" }
    methods:  GET

demarches_paqss_new:
    path:     /paqss/new
    defaults: { _controller: "HopitalBundle:Paqss:new" }
    methods:  [GET, POST]

demarches_paqss_edit:
    path:     /paqss/{id}/edit
    defaults: { _controller: "HopitalBundle:Paqss:edit" }
    methods:  [GET, POST]

demarches_paqss_delete:
    path:     paqss/{id}/delete
    defaults: { _controller: "HopitalBundle:Paqss:delete" }
    methods:  DELETE

demarches_paqssdivision_new:
    path:     /paqssdivision/new
    defaults: { _controller: "HopitalBundle:Paqss:newDivision" }
    methods:  [GET, POST]


demarches_paqssdivision_edit:
    path:     /paqssdivision/{id}/edit
    defaults: { _controller: "HopitalBundle:Paqss:editDivision" }
    methods:  [GET, POST]

demarches_paqssdivision_delete:
    path:     paqssdivision/{id}/delete
    defaults: { _controller: "HopitalBundle:Paqss:deleteDivision" }
    methods:  DELETE



demarches_processus_index:
    path:     /processus
    defaults: { _controller: "HopitalBundle:Processus:index" }
    methods:  GET

demarches_processus_index_admin:
    path:     /processus_admin
    defaults: { _controller: "HopitalBundle:Processus:index_admin" }
    methods:  GET

demarches_processus_index_show:
    path:     /{id}/processus_show
    defaults: { _controller: "HopitalBundle:Processus:index_show" }
    methods:  [GET, POST]

demarches_processus_new:
    path:     /processus/new
    defaults: { _controller: "HopitalBundle:Processus:new" }
    methods:  [GET, POST]

demarches_processus_edit:
    path:     /processus/{id}/edit
    defaults: { _controller: "HopitalBundle:Processus:edit" }
    methods:  [GET, POST]

demarches_processus_delete:
    path:     processus/{id}/delete
    defaults: { _controller: "HopitalBundle:Processus:delete" }
    methods:  DELETE

demarches_processuscategorie_new:
    path:     /processuscategorie/new
    defaults: { _controller: "HopitalBundle:Processus:newCategorie" }
    methods:  [GET, POST]

demarches_processuscategorie_edit:
    path:     /processuscategorie/{id}/edit
    defaults: { _controller: "HopitalBundle:Processus:editCategorie" }
    methods:  [GET, POST]

demarches_processuscategorie_delete:
    path:     processuscategorie/{id}/delete
    defaults: { _controller: "HopitalBundle:Processus:deleteCategorie" }
    methods:  DELETE


