demarches_certification_index:
    path:     /certification
    defaults: { _controller: "HopitalBundle:Certification:index" }
    methods:  GET

demarches_certification_new:
    path:     /certification/new
    defaults: { _controller: "HopitalBundle:Certification:new" }
    methods:  [GET, POST]

demarches_certification_edit:
    path:     /certification/{id}/edit
    defaults: { _controller: "HopitalBundle:Certification:edit" }
    methods:  [GET, POST]

demarches_certification_delete:
    path:     /certification/{id}/delete
    defaults: { _controller: "HopitalBundle:Certification:delete" }
    methods:  DELETE


demarches_epp:
    path:     /epp
    defaults: { _controller: "HopitalBundle:Demarches:epp" }
    methods:  GET





demarches_processus_index:
    path:     /processus
    defaults: { _controller: "HopitalBundle:Processus:index" }
    methods:  GET

demarches_processus_new:
    path:     /processus/new
    defaults: { _controller: "HopitalBundle:Processus:new" }
    methods:  [GET, POST]

demarches_processus_edit:
    path:     /processus/{id}/edit
    defaults: { _controller: "HopitalBundle:Processus:edit" }
    methods:  [GET, POST]

demarches_processus_delete:
    path:     processus/{id}/delete
    defaults: { _controller: "HopitalBundle:Processus:delete" }
    methods:  DELETE

demarches_processuscategorie_new:
    path:     /categorie/new
    defaults: { _controller: "HopitalBundle:Processus:newCategorie" }
    methods:  [GET, POST]






demarches_paqss_new:
    path:     /paqss/new
    defaults: { _controller: "HopitalBundle:Paqss:new" }
    methods:  [GET, POST]

demarches_paqss_edit:
    path:     /paqss/{id}/edit
    defaults: { _controller: "HopitalBundle:Paqss:edit" }
    methods:  [GET, POST]

demarches_paqss_index:
    path:     /paqss
    defaults: { _controller: "HopitalBundle:Paqss:index" }
    methods:  GET

demarches_paqss_delete:
    path:     /paqss/{id}/delete
    defaults: { _controller: "HopitalBundle:Paqss:delete" }
    methods:  DELETE

