documentation_note:
    path:     /note
    defaults: { _controller: "HopitalBundle:Documentation:note" }
    methods:  GET

documentation_noteservice:
    path:     /noteservice
    defaults: { _controller: "HopitalBundle:Documentation:noteservice" }
    methods:  GET

documentation_contacts:
    path:     /contacts
    defaults: { _controller: "HopitalBundle:Documentation:contacts" }
    methods:  GET

documentation_astreintes:
    path:     /astreintes
    defaults: { _controller: "HopitalBundle:Documentation:astreintes" }
    methods:  GET

documentation_journaux:
    path:     /journaux
    defaults: { _controller: "HopitalBundle:Documentation:journaux" }
    methods:  GET

documentation_basedoc:
    path:     /basedoc
    defaults: { _controller: "HopitalBundle:Documentation:basedoc" }
    methods:  GET

documentation_instances:
    path:     /instances
    defaults: { _controller: "HopitalBundle:Documentation:instances" }
    methods:  GET

documentation_groupe:
    path:     /groupe
    defaults: { _controller: "HopitalBundle:Documentation:groupe" }
    methods:  GET

documentation_fournisseurs:
    path:     /fournisseurs
    defaults: { _controller: "HopitalBundle:Documentation:fournisseurs" }
    methods:  GET

documentation_galerie_index:
    path:     /galerie
    defaults: { _controller: "HopitalBundle:Galerie:index" }
    methods:  GET

documentation_galerie_show:
    path:     /galerie/{id}/show
    defaults: { _controller: "HopitalBundle:Galerie:show" }
    methods:  GET

documentation_galerie_new:
    path:     /galerie/new
    defaults: { _controller: "HopitalBundle:Galerie:new" }
    methods:  [GET, POST]

documentation_galerie_edit:
    path:     /galerie/{id}/edit
    defaults: { _controller: "HopitalBundle:Galerie:edit" }
    methods:  [GET, POST]

documentation_delete:
    path:     /{id}/delete
    defaults: { _controller: "HopitalBundle:Galerie:delete" }
    methods:  DELETE