documentation_index:
    path:     /
    defaults: { _controller: "HopitalBundle:Documentation:index" }
    methods:  GET

documentation_show:
    path:     /{id}/show
    defaults: { _controller: "HopitalBundle:Documentation:show" }
    methods:  GET

documentation_new:
    path:     /new
    defaults: { _controller: "HopitalBundle:Documentation:new" }
    methods:  [GET, POST]

documentation_edit:
    path:     /{id}/edit
    defaults: { _controller: "HopitalBundle:Documentation:edit" }
    methods:  [GET, POST]

documentation_delete:
    path:     /{id}/delete
    defaults: { _controller: "HopitalBundle:Documentation:delete" }
    methods:  DELETE

documentation_note:
    path:     /note
    defaults: { _controller: "HopitalBundle:Documentation:note" }
    methods:  GET

documentation_noteservice:
    path:     /noteservice
    defaults: { _controller: "HopitalBundle:Documentation:noteservice" }
    methods:  GET

documentation_contacts:
    path:     /contacts
    defaults: { _controller: "HopitalBundle:Documentation:contacts" }
    methods:  GET

documentation_journaux:
    path:     /journaux
    defaults: { _controller: "HopitalBundle:Documentation:journaux" }
    methods:  GET

documentation_basedoc:
    path:     /basedoc
    defaults: { _controller: "HopitalBundle:Documentation:basedoc" }
    methods:  GET

documentation_instances:
    path:     /instances
    defaults: { _controller: "HopitalBundle:Documentation:instances" }
    methods:  GET

documentation_groupe:
    path:     /groupe
    defaults: { _controller: "HopitalBundle:Documentation:groupe" }
    methods:  GET

documentation_fournisseurs:
    path:     /fournisseurs
    defaults: { _controller: "HopitalBundle:Documentation:fournisseurs" }
    methods:  GET

documentation_galerie:
    path:     /galerie
    defaults: { _controller: "HopitalBundle:Documentation:galerie" }
    methods:  GET









documentation_astreintes_index:
    path:     /astreintes
    defaults: { _controller: "HopitalBundle:Astreintes:index" }
    methods:  GET

documentation_astreintes_show:
    path:     /astreintes/{id}/show
    defaults: { _controller: "HopitalBundle:Astreintes:show" }
    methods:  GET

documentation_astreintes_new:
    path:     /astreintes/new
    defaults: { _controller: "HopitalBundle:Astreintes:new" }
    methods:  [GET, POST]

documentation_astreintes_edit:
    path:     /astreintes/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:edit" }
    methods:  [GET, POST]

documentation_astreintes_delete:
    path:     /astreintes/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:delete" }
    methods:  DELETE


