documentation_note:
    path:     /note
    defaults: { _controller: "HopitalBundle:Documentation:note" }
    methods:  GET

documentation_noteservice:
    path:     /noteservice
    defaults: { _controller: "HopitalBundle:Documentation:noteservice" }
    methods:  GET

documentation_contacts:
    path:     /contacts
    defaults: { _controller: "HopitalBundle:Documentation:contacts" }
    methods:  GET

documentation_journaux:
    path:     /journaux
    defaults: { _controller: "HopitalBundle:Documentation:journaux" }
    methods:  GET

documentation_instances:
    path:     /instances
    defaults: { _controller: "HopitalBundle:Documentation:instances" }
    methods:  GET

documentation_groupe:
    path:     /groupe
    defaults: { _controller: "HopitalBundle:Documentation:groupe" }
    methods:  GET








documentation_astreintes_index:
    path:     /astreintes
    defaults: { _controller: "HopitalBundle:Astreintes:index" }
    methods:  GET

documentation_astreintesadministratif_show:
    path:     /astreintesadministratif/{id}/show
    defaults: { _controller: "HopitalBundle:Astreintes:showAdministratif" }
    methods:  GET

documentation_astreintesmedical_show:
    path:     /astreintesmedical/{id}/show
    defaults: { _controller: "HopitalBundle:Astreintes:showMedical" }
    methods:  GET

documentation_astreintescommune_show:
    path:     /astreintescommune/{id}/show
    defaults: { _controller: "HopitalBundle:Astreintes:showCommune" }
    methods:  GET

documentation_astreintestechnique_show:
    path:     /astreintestechnique/{id}/show
    defaults: { _controller: "HopitalBundle:Astreintes:showTechnique" }
    methods:  GET

documentation_astreintesadministratif_new:
    path:     /astreintesadministratif/new
    defaults: { _controller: "HopitalBundle:Astreintes:newAdministratif" }
    methods:  [GET, POST]

documentation_astreintesmedical_new:
    path:     /astreintesmedical/new
    defaults: { _controller: "HopitalBundle:Astreintes:newMedical" }
    methods:  [GET, POST]

documentation_astreintescommune_new:
    path:     /astreintescommune/new
    defaults: { _controller: "HopitalBundle:Astreintes:newCommune" }
    methods:  [GET, POST]

documentation_astreintestechnique_new:
    path:     /astreintestechnique/new
    defaults: { _controller: "HopitalBundle:Astreintes:newTechnique" }
    methods:  [GET, POST]

documentation_astreintesadministratif_edit:
    path:     /astreintesadministratif/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editAdministratif" }
    methods:  [GET, POST]

documentation_astreintesmedical_edit:
    path:     /astreintesmedical/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editMedical" }
    methods:  [GET, POST]

documentation_astreintescommune_edit:
    path:     /astreintescommune/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editCommune" }
    methods:  [GET, POST]

documentation_astreintestechnique_edit:
    path:     /astreintestechnique/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editTechnique" }
    methods:  [GET, POST]

documentation_astreintesadministratif_delete:
    path:     /astreintes/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteAdministratif" }
    methods:  DELETE

documentation_astreintesmedical_delete:
    path:     /astreintesmedical/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteMedical" }
    methods:  DELETE

documentation_astreintescommune_delete:
    path:     /astreintescommune/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteCommune" }
    methods:  DELETE

documentation_astreintestechnique_delete:
    path:     /astreintestechnique/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteTechnique" }
    methods:  DELETE



documentation_basedoc_index:
    path:     /basedoc
    defaults: { _controller: "HopitalBundle:Basedoc:index" }
    methods:  GET

documentation_basedoc_show:
    path:     /basedoc/{id}/show
    defaults: { _controller: "HopitalBundle:Basedoc:show" }
    methods:  GET

documentation_basedoc_new:
    path:     /basedoc/new
    defaults: { _controller: "HopitalBundle:Basedoc:new" }
    methods:  [GET, POST]

documentation_basedoc_edit:
    path:     /basedoc/{id}/edit
    defaults: { _controller: "HopitalBundle:Basedoc:edit" }
    methods:  [GET, POST]

documentation_basedoc_delete:
    path:     /basedoc/{id}/delete
    defaults: { _controller: "HopitalBundle:Basedoc:delete" }
    methods:  DELETE




documentation_fournisseur_index:
    path:     /fournisseur
    defaults: { _controller: "HopitalBundle:Fournisseur:index" }
    methods:  GET

documentation_fournisseur_show:
    path:     /fournisseur/{id}/show
    defaults: { _controller: "HopitalBundle:Fournisseur:show" }
    methods:  GET

documentation_fournisseur_new:
    path:     /fournisseur/new
    defaults: { _controller: "HopitalBundle:Fournisseur:new" }
    methods:  [GET, POST]

documentation_fournisseur_edit:
    path:     /fournisseur/{id}/edit
    defaults: { _controller: "HopitalBundle:Fournisseur:edit" }
    methods:  [GET, POST]

documentation_fournisseur_delete:
    path:     /fournisseur/{id}/delete
    defaults: { _controller: "HopitalBundle:Fournisseur:delete" }
    methods:  DELETE


documentation_galerie_index:
    path:     /galerie
    defaults: { _controller: "HopitalBundle:Galerie:index" }
    methods:  GET

documentation_galerie_show:
    path:     /galerie/{id}/show
    defaults: { _controller: "HopitalBundle:Galerie:show" }
    methods:  GET

documentation_galerie_new:
    path:     /galerie/new
    defaults: { _controller: "HopitalBundle:Galerie:new" }
    methods:  [GET, POST]

documentation_galerie_edit:
    path:     /galerie/{id}/edit
    defaults: { _controller: "HopitalBundle:Galerie:edit" }
    methods:  [GET, POST]

documentation_galerie_delete:
    path:     /galerie/{id}/delete
    defaults: { _controller: "HopitalBundle:Galerie:delete" }
    methods:  DELETE