documentation_noteservice_index:
    path:     /noteservice
    defaults: { _controller: "HopitalBundle:Noteservice:index" }
    methods:  GET

documentation_noteservice_new:
    path:     /noteservice/new
    defaults: { _controller: "HopitalBundle:Noteservice:new" }
    methods:  [GET, POST]

documentation_noteservice_edit:
    path:     /noteservice/{id}/edit
    defaults: { _controller: "HopitalBundle:Noteservice:edit" }
    methods:  [GET, POST]

documentation_noteservice_delete:
    path:     /noteservice/{id}/delete
    defaults: { _controller: "HopitalBundle:Noteservice:delete" }
    methods:  DELETE



documentation_contacts_index:
    path:     /contacts
    defaults: { _controller: "HopitalBundle:Contacts:index" }
    methods:  GET

documentation_contacts_new:
    path:     /contacts/new
    defaults: { _controller: "HopitalBundle:Contacts:new" }
    methods:  [GET, POST]

documentation_contacts_edit:
    path:     /contacts/{id}/edit
    defaults: { _controller: "HopitalBundle:Contacts:edit" }
    methods:  [GET, POST]

documentation_contacts_delete:
    path:     /contacts/{id}/delete
    defaults: { _controller: "HopitalBundle:Contacts:delete" }
    methods:  DELETE




documentation_instances:
    path:     /instances
    defaults: { _controller: "HopitalBundle:Documentation:instances" }
    methods:  GET




documentation_astreintes_index:
    path:     /astreintes
    defaults: { _controller: "HopitalBundle:Astreintes:index" }
    methods:  GET

documentation_astreintesadministratif_new:
    path:     /astreintesadministratif/new
    defaults: { _controller: "HopitalBundle:Astreintes:newAdministratif" }
    methods:  [GET, POST]

documentation_astreintesmedical_new:
    path:     /astreintesmedical/new
    defaults: { _controller: "HopitalBundle:Astreintes:newMedical" }
    methods:  [GET, POST]

documentation_astreintescommune_new:
    path:     /astreintescommune/new
    defaults: { _controller: "HopitalBundle:Astreintes:newCommune" }
    methods:  [GET, POST]

documentation_astreintestechnique_new:
    path:     /astreintestechnique/new
    defaults: { _controller: "HopitalBundle:Astreintes:newTechnique" }
    methods:  [GET, POST]

documentation_astreintesadministratif_edit:
    path:     /astreintesadministratif/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editAdministratif" }
    methods:  [GET, POST]

documentation_astreintesmedical_edit:
    path:     /astreintesmedical/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editMedical" }
    methods:  [GET, POST]

documentation_astreintescommune_edit:
    path:     /astreintescommune/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editCommune" }
    methods:  [GET, POST]

documentation_astreintestechnique_edit:
    path:     /astreintestechnique/{id}/edit
    defaults: { _controller: "HopitalBundle:Astreintes:editTechnique" }
    methods:  [GET, POST]

documentation_astreintesadministratif_delete:
    path:     /astreintes/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteAdministratif" }
    methods:  DELETE

documentation_astreintesmedical_delete:
    path:     /astreintesmedical/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteMedical" }
    methods:  DELETE

documentation_astreintescommune_delete:
    path:     /astreintescommune/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteCommune" }
    methods:  DELETE

documentation_astreintestechnique_delete:
    path:     /astreintestechnique/{id}/delete
    defaults: { _controller: "HopitalBundle:Astreintes:deleteTechnique" }
    methods:  DELETE





documentation_groupe_index:
    path:     /groupe
    defaults: { _controller: "HopitalBundle:Groupe:index" }
    methods:  GET
documentation_groupe_show:
    path:     /groupe/{id}/show
    defaults: { _controller: "HopitalBundle:Groupe:show" }
    methods:  [GET, POST]

documentation_groupe_new:
    path:     /groupe/new
    defaults: { _controller: "HopitalBundle:Groupe:new" }
    methods:  [GET, POST]

documentation_groupe_edit:
    path:     /groupe/{id}/edit
    defaults: { _controller: "HopitalBundle:Groupe:edit" }
    methods:  [GET, POST]

documentation_groupe_delete:
    path:     /groupe/{id}/delete
    defaults: { _controller: "HopitalBundle:Groupe:delete" }
    methods:  GET

documentation_groupemessage_delete:
    path:     /groupemessage/{id}/delete
    defaults: { _controller: "HopitalBundle:Groupe:deleteGroupeMessage" }
    methods:  DELETE



documentation_journaux_index:
    path:     /journaux
    defaults: { _controller: "HopitalBundle:Journaux:index" }
    methods:  GET

documentation_journaux_new:
    path:     /journaux/new
    defaults: { _controller: "HopitalBundle:Journaux:new" }
    methods:  [GET, POST]

documentation_journaux_edit:
    path:     /journaux/{id}/edit
    defaults: { _controller: "HopitalBundle:Journaux:edit" }
    methods:  [GET, POST]

documentation_journaux_delete:
    path:     /journaux/{id}/delete
    defaults: { _controller: "HopitalBundle:Journaux:delete" }
    methods:  DELETE




documentation_galerie_index:
    path:     /galerie
    defaults: { _controller: "HopitalBundle:Galerie:index" }
    methods:  GET

documentation_galerie_new:
    path:     /galerie/new
    defaults: { _controller: "HopitalBundle:Galerie:new" }
    methods:  [GET, POST]

documentation_galerie_edit:
    path:     /galerie/{id}/edit
    defaults: { _controller: "HopitalBundle:Galerie:edit" }
    methods:  [GET, POST]

documentation_galerie_delete:
    path:     galerie/{id}/delete
    defaults: { _controller: "HopitalBundle:Galerie:delete" }
    methods:  DELETE

documentation_galeriecategorie_new:
    path:     /categorie/new
    defaults: { _controller: "HopitalBundle:Galerie:newCategorie" }
    methods:  [GET, POST]




documentation_basedoc_index:
    path:     /basedoc
    defaults: { _controller: "HopitalBundle:Basedoc:index" }
    methods:  GET

documentation_basedoc_new:
    path:     /basedoc/new
    defaults: { _controller: "HopitalBundle:Basedoc:new" }
    methods:  [GET, POST]

documentation_basedoc_edit:
    path:     /basedoc/{id}/edit
    defaults: { _controller: "HopitalBundle:Basedoc:edit" }
    methods:  [GET, POST]

documentation_basedoc_delete:
    path:     /basedoc//{id}/delete
    defaults: { _controller: "HopitalBundle:Basedoc:delete" }
    methods:  DELETE



documentation_fournisseur_index:
    path:     /fournisseur
    defaults: { _controller: "HopitalBundle:Fournisseur:index" }
    methods:  GET

documentation_fournisseur_show:
    path:     /fournisseur/{id}/show
    defaults: { _controller: "HopitalBundle:Fournisseur:show" }
    methods:  GET

documentation_fournisseur_new:
    path:     /fournisseur/new
    defaults: { _controller: "HopitalBundle:Fournisseur:new" }
    methods:  [GET, POST]

documentation_fournisseur_edit:
    path:     /fournisseur/{id}/edit
    defaults: { _controller: "HopitalBundle:Fournisseur:edit" }
    methods:  [GET, POST]

documentation_fournisseur_delete:
    path:     /fournisseur/{id}/delete
    defaults: { _controller: "HopitalBundle:Fournisseur:delete" }
    methods:  DELETE



