personnel_index:
    path:     /
    defaults: { _controller: "HopitalBundle:Personnel:index" }
    methods:  GET

personnel_show:
    path:     /{id}/show
    defaults: { _controller: "HopitalBundle:Personnel:show" }
    methods:  GET

personnel_new:
    path:     /new
    defaults: { _controller: "HopitalBundle:Personnel:new" }
    methods:  [GET, POST]

personnel_edit:
    path:     /{id}/edit
    defaults: { _controller: "HopitalBundle:Personnel:edit" }
    methods:  [GET, POST]

personnel_delete:
    path:     /{id}/delete
    defaults: { _controller: "HopitalBundle:Personnel:delete" }
    methods:  DELETE

personnel_menu:
    path:     /menu
    defaults: { _controller: "HopitalBundle:Personnel:menu" }
    methods:  GET

personnel_postvacant:
    path:     /postvacant
    defaults: { _controller: "HopitalBundle:Personnel:postvacant" }
    methods:  GET

personnel_covoiturage:
    path:     /covoiturage
    defaults: { _controller: "HopitalBundle:Personnel:covoiturage" }
    methods:  GET

personnel_idees:
    path:     /idees
    defaults: { _controller: "HopitalBundle:Personnel:idees" }
    methods:  [GET, POST]



personnel_planniciel_index:
    path:     /planniciel
    defaults: { _controller: "HopitalBundle:Planniciel:index" }
    methods:  GET

personnel_planniciel_show:
    path:     /planniciel/{id}/show
    defaults: { _controller: "HopitalBundle:Planniciel:show" }
    methods:  GET

personnel_planniciel_new:
    path:     /planniciel/new
    defaults: { _controller: "HopitalBundle:Planniciel:new" }
    methods:  [GET, POST]

personnel_planniciel_edit:
    path:     /planniciel/{id}/edit
    defaults: { _controller: "HopitalBundle:Planniciel:edit" }
    methods:  [GET, POST]

personnel_planniciel_delete:
    path:     /planniciel/{id}/delete
    defaults: { _controller: "HopitalBundle:Planniciel:delete" }
    methods:  DELETE
