presentation_plans_index:
    path:     /plans
    defaults: { _controller: "HopitalBundle:Plans:index" }
    methods:  GET

presentation_plans_show:
    path:     /plans/{id}/show
    defaults: { _controller: "HopitalBundle:Plans:show" }
    methods:  GET

presentation_plans_new:
    path:     /plans/new
    defaults: { _controller: "HopitalBundle:Plans:new" }
    methods:  [GET, POST]

presentation_plans_edit:
    path:     /plans/{id}/edit
    defaults: { _controller: "HopitalBundle:Plans:edit" }
    methods:  [GET, POST]

presentation_delete:
    path:     /{id}/delete
    defaults: { _controller: "HopitalBundle:Plans:delete" }
    methods:  DELETE

presentation_livret:
    path:     /livret
    defaults: { _controller: "HopitalBundle:Presentation:livret" }
    methods:  GET

presentation_organigrammes:
    path:     /organigrammes
    defaults: { _controller: "HopitalBundle:Presentation:organigrammes" }
    methods:  GET




