recommandation_anesm_index:
    path:     /anesm
    defaults: { _controller: "HopitalBundle:Anesm:index" }
    methods:  GET

recommandation_anesm_new:
    path:     /anesm/new
    defaults: { _controller: "HopitalBundle:Anesm:new" }
    methods:  [GET, POST]

recommandation_anesm_edit:
    path:     /anesm/{id}/edit
    defaults: { _controller: "HopitalBundle:Anesm:edit" }
    methods:  [GET, POST]

recommandation_anesm_delete:
    path:     /anesm/{id}/delete
    defaults: { _controller: "HopitalBundle:Anesm:delete" }
    methods:  DELETE





recommandation_bulletinoff_index:
    path:     /bulletinoff
    defaults: { _controller: "HopitalBundle:Bulletinoff:index" }
    methods:  GET

recommandation_bulletinoff_new:
    path:     /bulletinoff/new
    defaults: { _controller: "HopitalBundle:Bulletinoff:new" }
    methods:  [GET, POST]

recommandation_bulletinoff_edit:
    path:     /bulletinoff/{id}/edit
    defaults: { _controller: "HopitalBundle:Bulletinoff:edit" }
    methods:  [GET, POST]

recommandation_bulletinoff_delete:
    path:     /bulletinoff/{id}/delete
    defaults: { _controller: "HopitalBundle:Bulletinoff:delete" }
    methods:  DELETE





recommandation_has_index:
    path:     /has
    defaults: { _controller: "HopitalBundle:Has:index" }
    methods:  GET

recommandation_has_new:
    path:     /has/new
    defaults: { _controller: "HopitalBundle:Has:new" }
    methods:  [GET, POST]

recommandation_has_edit:
    path:     /has/{id}/edit
    defaults: { _controller: "HopitalBundle:Has:edit" }
    methods:  [GET, POST]

recommandation_has_delete:
    path:     /has/{id}/delete
    defaults: { _controller: "HopitalBundle:Has:delete" }
    methods:  DELETE





recommandation_journaloff_index:
    path:     /journaloff
    defaults: { _controller: "HopitalBundle:Journaloff:index" }
    methods:  GET

recommandation_journaloff_new:
    path:     /journaloff/new
    defaults: { _controller: "HopitalBundle:Journaloff:new" }
    methods:  [GET, POST]

recommandation_journaloff_edit:
    path:     /journaloff/{id}/edit
    defaults: { _controller: "HopitalBundle:Journaloff:edit" }
    methods:  [GET, POST]

recommandation_journaloff_delete:
    path:     /journaloff/{id}/delete
    defaults: { _controller: "HopitalBundle:Journaloff:delete" }
    methods:  DELETE





recommandation_pagesjaunes_index:
    path:     /pagesjaunes
    defaults: { _controller: "HopitalBundle:Pagesjaunes:index" }
    methods:  GET

recommandation_pagesjaunes_new:
    path:     /pagesjaunes/new
    defaults: { _controller: "HopitalBundle:Pagesjaunes:new" }
    methods:  [GET, POST]

recommandation_pagesjaunes_edit:
    path:     /pagesjaunes/{id}/edit
    defaults: { _controller: "HopitalBundle:Pagesjaunes:edit" }
    methods:  [GET, POST]

recommandation_pagesjaunes_delete:
    path:     /pagesjaunes/{id}/delete
    defaults: { _controller: "HopitalBundle:Pagesjaunes:delete" }
    methods:  DELETE


