Sacha\IuchBundle\Entity\Service:
    type: entity
    repositoryClass: Sacha\IuchBundle\Entity\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        uf:
            type: string
            length: 4
            unique: true
        email:
            type: string
            length: 255
        telephone:
            type: string
            length: 64

# Service Référend
    oneToMany:
        users:
            targetEntity: Sacha\Application\Sonata\UserBundle\Entity\User
            mappedBy: service
# Chef service

    oneToOne:
        chef_service:
            targetEntity: Sacha\Application\Sonata\UserBundle\Entity\User
            orphanRemoval: true
            joinColumn:
                name: chef_service
                referencedColumnName: id
                onDelete: SET NULL

    lifecycleCallbacks: { }
