hopital_accueil:
    resource: "@HopitalBundle/Resources/config/routing/accueil.yml"
    prefix:   /accueil

hopital_homepage:
    path:     /
    defaults: { _controller: HopitalBundle:Default:index }
