hopital:
    resource: "@HopitalBundle/Resources/config/routing.yml"
    prefix:   /

agenda:
    resource: "@VlAgendaBundle/Resources/config/routing.yml"
    prefix:   /

annonce:
    resource: "@VlAnnonceBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
