# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:

#    parameter_name: value

services:

    ### Setting up the SonataUser profile's form ###
    sonata.user.profile.form.type:
        class: Sacha\Application\Sonata\UserBundle\Form\Type\ProfileType
        arguments: ["Sacha\Application\Sonata\UserBundle\Entity\User"]
        tags:
            - { name: "form.type", alias: "application_sonata_user_profile"}

    ### Login Listener for after login redirection ###
    redirect.after.login:
        class: Sacha\IuchBundle\Redirection\AfterLoginRedirection
        arguments: [@router, @security.context]

    ### Disabling SonataUser groups // Cause we dont need.. ###
    sonata.user.admin.group:
        abstract: true
        public: false

    ### To check if first connexion redirection ###
    login_listener:
        class: 'Sacha\Application\Sonata\UserBundle\EventListener\LoginListener'
        arguments: ['@security.authorization_checker', '@router', '@event_dispatcher']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }

    application.sonata_user_listener:
        class: Sacha\Application\Sonata\UserBundle\EventListener\editProfileListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
        arguments:
            - @mailer
            - @service_container