HopitalBundle\Entity\Amicale:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\AmicaleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
