HopitalBundle\Entity\Anesm:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\AnesmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
