HopitalBundle\Entity\Anesm:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\AnesmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO



    fields:
        anesmimg:
            type: string
            length: 25
            nullable: true
        anesmurl:
            type: string
            length: 255
            nullable: true
        anesmtitle:
            type: string
            length: 255
            nullable: true
        anesmdescription:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]

