HopitalBundle\Entity\Articles:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\ArticlesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
