HopitalBundle\Entity\Articles:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\ArticlesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        articlesimg:
            type: string
            length: 25
            nullable: true
        titlearticles:
            type: string
            length: 255
        idarticles:
            type: string
            length: 255



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]