HopitalBundle\Entity\Astreintes:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\AstreintesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
