HopitalBundle\Entity\Basedoc:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\BasedocRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        basedocimg:
            type: string
            length: 25
            nullable: true
    manyToOne:
        division:
            targetEntity: HopitalBundle\Entity\BasedocOption
            inversedBy: photos
            joinColumn:
                onDelete: CASCADE



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]