HopitalBundle\Entity\BasedocOption:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\BasedocOptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        division:
            type: string
            length: 255

    oneToMany:
        photos:
            targetEntity: HopitalBundle\Entity\Basedoc
            mappedBy: division
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks: { }