HopitalBundle\Entity\Bulletinoff:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\BulletinoffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
