HopitalBundle\Entity\Certifications:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\CertificationsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
