HopitalBundle\Entity\Cgos:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\CgosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
