HopitalBundle\Entity\Communication:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\CommunicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
