HopitalBundle\Entity\Contacts:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\ContactsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
