HopitalBundle\Entity\Covoiturage:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\CovoiturageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO



    fields:
        covoiturageimg:
            type: string
            length: 25
            nullable: true
        covoiturageurl:
            type: string
            length: 255
            nullable: true
        covoituragetitle:
            type: string
            length: 255
            nullable: true
        covoituragedescription:
            type: string
            length: 255
            nullable: true


    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]

