HopitalBundle\Entity\Direction:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\DirectionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
