HopitalBundle\Entity\Epp:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\EppRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        epp1:
            type: string
            length: 25
            nullable: true
    manyToOne:
        rubrique:
            targetEntity: HopitalBundle\Entity\EppRubrique
            inversedBy: photos

    lifecycleCallbacks:
        prePersist: [ preUpload, preUpload1 ]
        preUpdate: [ preUpload, preUpload1 ]
        postPersist: [ upload, upload1 ]
        postUpdate: [ upload, upload1 ]
        postRemove: [ removeUpload, removeUpload1, ]