HopitalBundle\Entity\Epp:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\EppRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
