HopitalBundle\Entity\EppRubrique:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\EppRubriqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rubrique:
            type: string
            length: 255
    oneToMany:
        photos:
            targetEntity: HopitalBundle\Entity\Epp
            mappedBy: rubrique

    lifecycleCallbacks: { }