HopitalBundle\Entity\Fournisseur:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\FournisseurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        fournisseur1:
            type: string
            length: 25
            nullable: true

    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1, ]