HopitalBundle\Entity\Galerie:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\GalerieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields :
        galerie1:
            type: string
            lenght: 255
            nullable: TRUE
    lifecycleCallbacks: {  }
