HopitalBundle\Entity\Galerie:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\GalerieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        galerie1:
            type: string
            length: 25
            nullable: true
        categorie:
            type: string
            length: 255


    lifecycleCallbacks:
        prePersist: [ preUpload, preUpload1 ]
        preUpdate: [ preUpload, preUpload1 ]
        postPersist: [ upload, upload1 ]
        postUpdate: [ upload, upload1 ]
        postRemove: [ removeUpload, removeUpload1, ]