HopitalBundle\Entity\Ght:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\GhtRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        ghtimg:
            type: string
            length: 25
            nullable: true
        titleght:
            type: string
            length: 255
        idght:
            type: string
            length: 255



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]