HopitalBundle\Entity\Ght:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\GhtRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
