HopitalBundle\Entity\Groupe:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\GroupeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
    oneToMany:
        groupemessage:
            targetEntity: HopitalBundle\Entity\Groupe
            mappedBy: groupes
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks: {  }

