HopitalBundle\Entity\Has:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\HasRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
