HopitalBundle\Entity\Idees:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\IdeesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> book

    fields:
        ideestitle:
            type: string
            length: 50

<<<<<<< HEAD
=======
>>>>>>> b5081c74eadd43691d274f1232309d8ee62c399b
>>>>>>> book
    lifecycleCallbacks: {  }