HopitalBundle\Entity\Idees:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\IdeesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }