HopitalBundle\Entity\Instances:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\InstancesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
