HopitalBundle\Entity\Lettreinfo:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\LettreinfoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        lettreinfoimg:
            type: string
            length: 25
            nullable: true
        titlelettreinfo:
            type: string
            length: 255
        idlettreinfo:
            type: string
            length: 255



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]