HopitalBundle\Entity\Menu:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\MenuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO



    fields:
        titlemenu1:
            type: string
            length: 255
            nullable: true
        titlemenu2:
            type: string
            length: 255
            nullable: true
        titlemenu3:
            type: string
            length: 255
            nullable: true
        titlemenu4:
            type: string
            length: 255
            nullable: true
        titlemenurempl:
            type: string
            length: 255
            nullable: true
        menuimg:
            type: string
            length: 25
            nullable: true
        menu1img:
            type: string
            length: 25
            nullable: true
        menu2img:
            type: string
            length: 25
            nullable: true
        menu3img:
            type: string
            length: 25
            nullable: true
        menu4img:
            type: string
            length: 25
            nullable: true
        menuimgrempl:
            type: string
            length: 25
            nullable: true



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1, preUpload2 ]
      preUpdate: [ preUpload, preUpload1, preUpload2 ]
      postPersist: [ upload, upload1, upload2 ]
      postUpdate: [ upload, upload1, upload2 ]
      postRemove: [ removeUpload, removeUpload1, removeUpload2 ]

