HopitalBundle\Entity\Noteservice:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\NoteserviceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
