HopitalBundle\Entity\Noteservice:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\NoteserviceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        noteserviceimg:
            type: string
            length: 25
            nullable: true
        titlenoteservice:
            type: string
            length: 255
        idnoteservice:
            type: string
            length: 255



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]