HopitalBundle\Entity\Organigrammes:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\OrganigrammesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
