HopitalBundle\Entity\Pagesjaunes:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PagesjaunesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO



    fields:
        pagesjaunesimg:
            type: string
            length: 25
            nullable: true
        pagesjaunesurl:
            type: string
            length: 255
            nullable: true
        pagesjaunestitle:
            type: string
            length: 255
            nullable: true
        pagesjaunesdescription:
            type: string
            length: 255
            nullable: true



    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload1 ]
      preUpdate: [ preUpload, preUpload1 ]
      postPersist: [ upload, upload1 ]
      postUpdate: [ upload, upload1 ]
      postRemove: [ removeUpload, removeUpload1 ]
