HopitalBundle\Entity\Pagesjaunes:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PagesjaunesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
