HopitalBundle\Entity\Paqss:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PaqssRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        paqss1:
            type: string
            length: 25
            nullable: true


    manyToOne:
        rubrique:
            targetEntity: HopitalBundle\Entity\PaqssRubrique
            inversedBy: photos

    lifecycleCallbacks:
        prePersist: [ preUpload, preUpload1 ]
        preUpdate: [ preUpload, preUpload1 ]
        postPersist: [ upload, upload1 ]
        postUpdate: [ upload, upload1 ]
        postRemove: [ removeUpload, removeUpload1, ]