HopitalBundle\Entity\Paqss:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PaqssRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
