HopitalBundle\Entity\Personnel:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PersonnelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
