HopitalBundle\Entity\Petitesannonces:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PetitesannoncesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
