HopitalBundle\Entity\Planniciel:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PlannicielRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
