HopitalBundle\Entity\Presentation:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\PresentationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
