HopitalBundle\Entity\Processus:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\ProcessusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
