HopitalBundle\Entity\Processus:
    type: entity
    table: null
    repositoryClass: HopitalBundle\Repository\ProcessusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    fields:
        processus1:
            type: string
            length: 25
            nullable: true
    manyToOne:
        categorie:
            targetEntity: HopitalBundle\Entity\ProcessusCategorie
            inversedBy: photos
            joinColumn:
            onDelete: CASCADE

    lifecycleCallbacks:
        prePersist: [ preUpload, preUpload1 ]
        preUpdate: [ preUpload, preUpload1 ]
        postPersist: [ upload, upload1 ]
        postUpdate: [ upload, upload1 ]
        postRemove: [ removeUpload, removeUpload1, ]