services:
    sonata.infomail:
        class: Sacha\InfoMailBundle\Admin\InfoMailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.mails", label: "Mail d'information"}
        arguments:
            - ~
            - Sacha\InfoMailBundle\Entity\InfoMail
            - Sacha\InfoMailBundle:InfoMail
        calls:
            - [ setTemplate, [ show, InfoMailBundle:infoMail:show.html.twig ]]
            - [ setTemplate, [ list, InfoMailBundle:infoMail:list.html.twig ]]