Vl\AnnonceBundle\Entity\Amicale:
    type: entity
    table: null
    repositoryClass: Vl\AnnonceBundle\Repository\AmicaleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        description:
            type: string
            length: 255
        auteur:
            type: string
            length: 255
        image:
            type: string
            length: 255
        prix:
            type: integer


    manyToOne:
          service:
              targetEntity: IuchBundle\Entity\Service
              inversedBy: id

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]